//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIB_FORMS_OB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT
    {
        public string ACCOUNTID { get; set; }
        public string PRODUCTID { get; set; }
        public string ISOCURRENCYCODE { get; set; }
        public string PSEUDONAME { get; set; }
        public string ACCOUNTDESCRIPTION { get; set; }
        public string ACCOUNTNAME { get; set; }
        public Nullable<decimal> CLEAREDBALANCE { get; set; }
        public Nullable<decimal> BOOKEDBALANCE { get; set; }
        public Nullable<decimal> CHEQUEDEPOSITBALANCE { get; set; }
        public Nullable<System.DateTime> LASTINTERESTACCRUALDATE { get; set; }
        public Nullable<decimal> CREDITLIMIT { get; set; }
        public Nullable<decimal> DEBITLIMIT { get; set; }
        public string JOINTACCOUNT { get; set; }
        public Nullable<System.DateTime> OPENDATE { get; set; }
        public string OPENEDBYUSER { get; set; }
        public Nullable<System.DateTime> LASTSTATICAMENDMENTDATE { get; set; }
        public string AMENDEDBYUSER { get; set; }
        public Nullable<System.DateTime> LASTTRANSACTIONDATE { get; set; }
        public string STOPPED { get; set; }
        public string STOPPEDBYUSER { get; set; }
        public Nullable<System.DateTime> STOPDATE { get; set; }
        public string STOPREASON { get; set; }
        public string STOPCODE { get; set; }
        public string CLOSED { get; set; }
        public Nullable<System.DateTime> CLOSUREDATE { get; set; }
        public Nullable<System.DateTime> DATEOFDORMANCY { get; set; }
        public string DORMANTSTATUS { get; set; }
        public Nullable<decimal> MINOPENINGBALANCEAMOUNT { get; set; }
        public Nullable<decimal> LOWESTBALANCE { get; set; }
        public Nullable<System.DateTime> LOWESTBALANCEDATE { get; set; }
        public string PASSBOOKINDICATOR { get; set; }
        public string FEEWAIVEINDICATOR { get; set; }
        public Nullable<int> LIMITEXCESSACTION { get; set; }
        public Nullable<int> LIMITINDICATOR { get; set; }
        public string LIMITREF1 { get; set; }
        public string LIMITREF2 { get; set; }
        public string LIMITREF3 { get; set; }
        public string LIMITREF4 { get; set; }
        public string LIMITREF5 { get; set; }
        public Nullable<System.DateTime> LIMITREVIEWDATE { get; set; }
        public Nullable<System.DateTime> LIMITEXPIRYDATE { get; set; }
        public Nullable<System.DateTime> LASTCREDITLIMITCHANGEDATE { get; set; }
        public Nullable<System.DateTime> LASTDEBITLIMITCHANGEDATE { get; set; }
        public string TAXINDICATORCR { get; set; }
        public string TAXINDICATORDR { get; set; }
        public string PEROUTERPROFILEID { get; set; }
        public Nullable<int> STANDINGORDER { get; set; }
        public Nullable<int> SERVICEFEE { get; set; }
        public Nullable<int> TAXATION { get; set; }
        public Nullable<int> VERSIONNUM { get; set; }
        public Nullable<System.DateTime> DORMANTREACTIVATIONDATE { get; set; }
        public Nullable<decimal> BLOCKEDBALANCE { get; set; }
        public Nullable<System.DateTime> LASTINTHISTSTRIPDATE { get; set; }
        public Nullable<System.DateTime> LASTTRANSHISTSTRIPDATE { get; set; }
        public Nullable<System.DateTime> ACCOUNTTAKEONDATE { get; set; }
        public Nullable<decimal> ACCRIGHTSINDICATOR { get; set; }
        public string ACCOUNTSTYLE { get; set; }
        public string CHARGEFUNDINGACCOUNTID { get; set; }
        public Nullable<System.DateTime> LASTCREDITTRANSDTTM { get; set; }
        public Nullable<System.DateTime> LASTDEBITTRANSDTTM { get; set; }
        public Nullable<decimal> TEMPACCOUNTLIMIT { get; set; }
        public Nullable<System.DateTime> TEMPLIMEXPIRYDATE { get; set; }
        public string PRODUCTCONTEXTCODE { get; set; }
        public string BRANCHSORTCODE { get; set; }
        public Nullable<int> UBACCTRANSCOUNTER { get; set; }
        public string UBACCOUNTSTATUS { get; set; }
        public string UBISARCHIVE { get; set; }
        public string UBISDELETE { get; set; }
        public string UBCUSTOMERCODE { get; set; }
        public string UBACCRIGHTSINDREASON { get; set; }
        public Nullable<System.DateTime> UBACCRIGHTSINDCHANGEDT { get; set; }
        public string UBACCRIGHTSINDCHANGEDBY { get; set; }
        public string UBINDUSTRYCODE { get; set; }
    }
}
