//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIB_FORMS_OB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BFTB_BRANCH
    {
        public string BFBRANCHSORTCODEPK { get; set; }
        public string BFBRANCHNAME { get; set; }
        public string BFCONTACTPERSON { get; set; }
        public string BFCONTACTNUMBER { get; set; }
        public string BFADDRESSLINE1 { get; set; }
        public string BFADDRESSLINE2 { get; set; }
        public string BFADDRESSLINE3 { get; set; }
        public string BFADDRESSLINE4 { get; set; }
        public string BFADDRESSLINE5 { get; set; }
        public string BFADDRESSLINE6 { get; set; }
        public string BFADDRESSLINE7 { get; set; }
        public string BFPOSTZIPCODE { get; set; }
        public string BFALPHACODE { get; set; }
        public string BFBANKNAME { get; set; }
        public string BFLANGUAGELOCALE { get; set; }
        public string BFVARIANTLOCALE { get; set; }
        public string BFCOUNTRYLOCALE { get; set; }
        public Nullable<int> BFRANGEFROM { get; set; }
        public Nullable<int> BFRANGETO { get; set; }
        public Nullable<int> BFCURRENTVALUE { get; set; }
        public string BFDEPLOYED { get; set; }
        public Nullable<int> BFCLEARINGDAYS { get; set; }
        public Nullable<int> VERSIONNUM { get; set; }
        public string BFBMBRANCH { get; set; }
        public string BFIMDCODE { get; set; }
        public string BFISOCOUNTRYCODE { get; set; }
        public string BFBICCODE { get; set; }
        public string BFZONE { get; set; }
        public string BFBRANCHTIMEZONE { get; set; }
    }
}
