//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIB_FORMS_OB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AIBSITEntities : DbContext
    {
        public AIBSITEntities()
            : base("name=AIBSITEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ACCOUNT> ACCOUNTs { get; set; }
        public DbSet<EXCHANGERATE> EXCHANGERATES { get; set; }
        public DbSet<EXCHANGERATESHISTORY> EXCHANGERATESHISTORies { get; set; }
        public DbSet<BFTB_BRANCH> BFTB_BRANCH { get; set; }
        public DbSet<CUSTOMERBRANCH> CUSTOMERBRANCHes { get; set; }
    }
}
