//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIB_FORMS_OB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXCHANGERATE
    {
        public string CURRENCYRATEID { get; set; }
        public string FROMCURRENCYCODE { get; set; }
        public string TOCURRENCYCODE { get; set; }
        public string EXCHANGERATETYPE { get; set; }
        public string MULTIPLYDIVIDE { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public Nullable<decimal> TOLERANCE { get; set; }
        public Nullable<decimal> RATE { get; set; }
        public Nullable<decimal> LIMIT1 { get; set; }
        public Nullable<decimal> RATE2 { get; set; }
        public Nullable<decimal> LIMIT2 { get; set; }
        public string REFER2 { get; set; }
        public Nullable<decimal> RATE3 { get; set; }
        public Nullable<decimal> LIMIT3 { get; set; }
        public string REFER3 { get; set; }
        public Nullable<decimal> RATE4 { get; set; }
        public Nullable<decimal> LIMIT4 { get; set; }
        public string REFER4 { get; set; }
        public Nullable<decimal> RATE5 { get; set; }
        public Nullable<decimal> LIMIT5 { get; set; }
        public string REFER5 { get; set; }
        public Nullable<decimal> RATE6 { get; set; }
        public Nullable<decimal> LIMIT6 { get; set; }
        public string REFER6 { get; set; }
        public Nullable<int> VERSIONNUM { get; set; }
        public Nullable<short> SPOTPERIODINDAYS { get; set; }
    }
}
